
MapSeven:
  Piwik:
    host: null
    token_auth: null
Neos:
  Neos:
    modules:
      management:
        submodules:
          piwik:
            label: Piwik
            controller: \MapSeven\Piwik\Controller\Module\Management\PiwikController
            description: 'Configure Piwik for your Domains'
            icon: icon-bar-chart
            actions:
              index:
                label: 'Configure piwik'
                title: 'Configure piwik'
    fusion:
      autoInclude:
        MapSeven.Piwik: true
